# Generated by Django 6.0.2 on 2026-02-19 18:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Investimentos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("banco", models.CharField(max_length=50)),
                ("ativo", models.CharField(max_length=8)),
                ("quantidade", models.IntegerField()),
                ("valor_compra", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name="faturas",
            name="limite_total",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="faturas",
            name="valor_inicial",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="faturas",
            name="vencimento",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
