# Generated by Django 6.0.2 on 2026-02-20 17:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_atualizar_lançamento"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lancamento",
            options={
                "ordering": ["-data", "-created_at"],
                "verbose_name": "Lançamento",
                "verbose_name_plural": "Lançamentos",
            },
        ),
        migrations.RemoveField(
            model_name="lancamento",
            name="status",
        ),
        migrations.AddField(
            model_name="lancamento",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Criado em",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lancamento",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
        ),
        migrations.AlterField(
            model_name="lancamento",
            name="categoria",
            field=models.CharField(max_length=100, verbose_name="Categoria"),
        ),
        migrations.AlterField(
            model_name="lancamento",
            name="data",
            field=models.DateField(verbose_name="Data"),
        ),
        migrations.AlterField(
            model_name="lancamento",
            name="descricao",
            field=models.CharField(max_length=255, verbose_name="Descrição"),
        ),
        migrations.AlterField(
            model_name="lancamento",
            name="metodo_pagamento",
            field=models.CharField(
                choices=[
                    ("PIX", "PIX"),
                    ("CREDITO_NUBANK", "Cartão Crédito Nubank"),
                    ("CREDITO_BRB", "Cartão Crédito BRB"),
                    ("CREDITO_C&A", "Cartão Crédito C&A"),
                    ("CREDITO_MERCADO_PAGO", "Cartão Crédito Mercado Pago"),
                    ("PREVISIONADO", "Previsionado"),
                ],
                help_text="Como foi pago ou recebido",
                max_length=50,
                verbose_name="Método de Pagamento",
            ),
        ),
        migrations.AlterField(
            model_name="lancamento",
            name="tipo",
            field=models.CharField(
                choices=[("ENTRADA", "Entrada"), ("SAIDA", "Saída")],
                help_text="Entrada (receita) ou Saída (despesa)",
                max_length=20,
                verbose_name="Tipo",
            ),
        ),
        migrations.AlterField(
            model_name="lancamento",
            name="valor",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Valor"
            ),
        ),
        migrations.AddIndex(
            model_name="lancamento",
            index=models.Index(
                fields=["tipo", "data"], name="core_lancam_tipo_c3f9fa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lancamento",
            index=models.Index(
                fields=["categoria", "tipo"], name="core_lancam_categor_078b10_idx"
            ),
        ),
    ]
