# Generated by Django 6.0.2 on 2026-02-23 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_lancamento_options_remove_lancamento_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lancamento",
            name="ano_referencia",
            field=models.IntegerField(
                blank=True, help_text="Ano de referência da fatura", null=True
            ),
        ),
        migrations.AddField(
            model_name="lancamento",
            name="mes_referencia",
            field=models.IntegerField(
                blank=True, help_text="Mês de referência da fatura", null=True
            ),
        ),
        migrations.AddField(
            model_name="lancamento",
            name="origem",
            field=models.CharField(
                choices=[("MANUAL", "Manual"), ("PDF", "PDF"), ("CSV", "CSV")],
                default="MANUAL",
                max_length=10,
            ),
        ),
    ]
