# Generated by Django 6.0.2 on 2026-02-23 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_lancamento_ano_referencia_lancamento_mes_referencia_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lancamento",
            name="is_recorrente",
            field=models.BooleanField(
                default=False,
                help_text="Se este lançamento foi criado por uma recorrência",
            ),
        ),
        migrations.AddField(
            model_name="lancamento",
            name="recorrencia_origem_id",
            field=models.IntegerField(
                blank=True,
                help_text="ID da recorrência que gerou este lançamento",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="lancamento",
            name="status_pagamento",
            field=models.CharField(
                choices=[
                    ("PAGO", "Pago"),
                    ("PREVISIONADO", "Previsionado"),
                    ("PENDENTE", "Pendente"),
                ],
                default="PAGO",
                help_text="Status do pagamento",
                max_length=20,
            ),
        ),
    ]
